openapi: 3.0.0
info:
  title: Amazon Scraper API
  description: API Serverless para capturar e armazenar os produtos mais vendidos da Amazon.
  version: 1.0.0
servers:
  - url: https://5p7ew83tf7.execute-api.sa-east-1.amazonaws.com/dev
    description: API Gateway Serverless

paths:
  /departamentos:
    get:
      summary: Listar Departamentos
      tags:
        - Departamentos
      description: Retorna uma lista de todos os departamentos armazenados no banco de dados.
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  body:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        nome:
                          type: string
                        href:
                          type: string
        '500':
          description: Erro no servidor

  /produtos:
    get:
      summary: Listar Produtos Mais Vendidos
      tags:
        - Produtos
      description: Retorna a lista de produtos mais vendidos em todos os departamentos.
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  body:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        nome:
                          type: string
                        preco:
                          type: string
                        estrelas:
                          type: string
                        tipo_tabela_pai:
                          type: string
                        id_tabela_pai:
                          type: string
        '500':
          description: Erro no servidor

  /departamentos/{id_departamento}:
    get:
      summary: Listar Produtos Mais Vendidos por Departamento
      tags:
        - Departamentos
      description: Retorna os produtos mais vendidos de um departamento específico.
      parameters:
        - name: id_departamento
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  body:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        nome:
                          type: string
                        preco:
                          type: string
                        estrelas:
                          type: string
                        tipo_tabela_pai:
                          type: string
                        id_tabela_pai:
                          type: string
        '400':
          description: ID do departamento ausente
        '500':
          description: Erro no servidor